name: warehouse-iotsys
services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: iotsys-mssql
    user: root
    ports:
      - "14331:1433"
    environment:
      - SA_PASSWORD=Abcd@1234
      - ACCEPT_EULA=Y
